"use client";

import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { Suspense, useEffect, useState } from "react";

const T = {
  fr: {
    ready: "Votre guide est prêt !",
    generated: "Votre guide de voyage",
    generated2: "a été généré avec succès.",
    emailSent: "Une copie a été envoyée à",
    downloadTitle: "Télécharger votre guide PDF",
    downloadSub: "· Format PDF",
    downloadBtn: "Télécharger mon guide PDF",
    emailFallback: "Votre guide vous a été envoyé par email.",
    warning: "Avertissement :",
    warningText: "Ce guide a été généré par intelligence artificielle. Les informations fournies sont données à titre indicatif et peuvent ne pas être exactes ou à jour. Vérifiez les horaires, prix et disponibilités directement auprès des établissements avant votre départ.",
    emailInfo: "Email envoyé à",
    emailInfo2: "avec le PDF en pièce jointe.",
    orderAnother: "Commander un autre guide →",
    footer: "© 2026 Travel IA — Guides de voyage personnalisés par IA",
  },
  en: {
    ready: "Your guide is ready!",
    generated: "Your travel guide for",
    generated2: "has been generated successfully.",
    emailSent: "A copy was sent to",
    downloadTitle: "Download your PDF guide",
    downloadSub: "· PDF format",
    downloadBtn: "Download my PDF guide",
    emailFallback: "Your guide was sent to you by email.",
    warning: "Disclaimer:",
    warningText: "This guide was generated by artificial intelligence. The information provided is for guidance only and may not be accurate or up to date. Please verify opening hours, prices, and availability directly with the establishments before your trip.",
    emailInfo: "Email sent to",
    emailInfo2: "with the PDF attached.",
    orderAnother: "Order another guide →",
    footer: "© 2026 Travel IA — AI-powered personalized travel guides",
  },
};

function SuccessContent() {
  const params = useSearchParams();
  const guideId = params.get("id");
  const email = params.get("email");
  const destination = params.get("destination");
  const [lang, setLang] = useState<"fr" | "en">("fr");
  const t = T[lang];

  const downloadUrl = guideId ? `/api/download-guide/${guideId}` : null;

  useEffect(() => {
    localStorage.removeItem("tgai_promo");
  }, []);

  return (
    <div className="min-h-screen flex flex-col" style={{ background: "var(--cb)", fontFamily: "var(--font-dm-sans), system-ui, sans-serif" }}>
      <header className="border-b" style={{ background: "var(--cc)", borderColor: "var(--ce)" }}>
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-lg font-bold" style={{ fontFamily: "var(--font-playfair), Georgia, serif", color: "var(--ct)" }}>
            Travel IA
          </Link>
          <div className="flex items-center gap-1 rounded-lg p-1" style={{ background: "var(--cb)", border: "1px solid var(--ce)" }}>
            {(["fr", "en"] as const).map(l => (
              <button key={l} onClick={() => setLang(l)}
                className="rounded-md px-2 py-0.5 text-xs font-bold transition-all"
                style={lang === l ? { background: "var(--ce)", color: "var(--ct)" } : { color: "var(--cm)", opacity: 0.6 }}>
                {l === "fr" ? "🇫🇷 FR" : "🇬🇧 EN"}
              </button>
            ))}
          </div>
        </div>
      </header>

      <main className="flex-1 flex items-center justify-center px-6 py-16">
        <div className="max-w-lg w-full text-center">
          <div className="w-20 h-20 rounded-full bg-emerald-950/40 border border-emerald-800/40 flex items-center justify-center mx-auto mb-8">
            <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#4ade80" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="20 6 9 17 4 12"/>
            </svg>
          </div>

          <h1 className="text-3xl lg:text-4xl font-bold mb-4" style={{ fontFamily: "var(--font-playfair), Georgia, serif", color: "var(--ct)" }}>
            {t.ready}
          </h1>

          <p className="mb-8 leading-relaxed" style={{ color: "var(--cm)" }}>
            {destination && (
              <>
                {t.generated}{" "}
                <strong style={{ color: "var(--cs)" }}>{destination}</strong>{" "}
                {t.generated2}
                <br />
              </>
            )}
            {email && (
              <>
                {t.emailSent}{" "}
                <strong style={{ color: "var(--cs)" }}>{email}</strong>.
              </>
            )}
          </p>

          <div className="rounded-2xl border p-8 mb-8" style={{ background: "var(--cc)", borderColor: "var(--ce)" }}>
            <div className="w-12 h-12 rounded-xl flex items-center justify-center mx-auto mb-4" style={{ background: "var(--caf)", border: "1px solid var(--cab)", color: "var(--ca)" }}>
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
                <line x1="16" y1="13" x2="8" y2="13"/>
                <line x1="16" y1="17" x2="8" y2="17"/>
                <polyline points="10 9 9 9 8 9"/>
              </svg>
            </div>
            <h2 className="text-lg font-bold mb-2" style={{ color: "var(--ct)", fontFamily: "var(--font-playfair), Georgia, serif" }}>
              {t.downloadTitle}
            </h2>
            <p className="text-sm mb-6" style={{ color: "var(--cm)" }}>
              {destination ? `Guide ${destination}` : (lang === "fr" ? "Votre guide personnalisé" : "Your personalized guide")}{t.downloadSub}
            </p>

            {downloadUrl ? (
              <a href={downloadUrl} download
                className="inline-flex items-center gap-2 font-bold px-8 py-4 rounded-xl transition-all text-base w-full justify-center"
                style={{ background: "var(--ca)", color: "var(--cat)" }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                  <polyline points="7 10 12 15 17 10"/>
                  <line x1="12" y1="15" x2="12" y2="3"/>
                </svg>
                {t.downloadBtn}
              </a>
            ) : (
              <p className="text-sm rounded-xl p-3" style={{ color: "var(--ca)", background: "var(--caf)", border: "1px solid var(--cab)" }}>
                {t.emailFallback}
              </p>
            )}
          </div>

          {email && (
            <div className="border rounded-xl px-6 py-4 mb-8 text-left" style={{ background: "var(--cc)", borderColor: "var(--ce)" }}>
              <div className="flex items-center gap-2 text-sm" style={{ color: "var(--cm)" }}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
                  <polyline points="22,6 12,13 2,6"/>
                </svg>
                <span>
                  {t.emailInfo} <strong style={{ color: "var(--cs)" }}>{email}</strong> {t.emailInfo2}
                </span>
              </div>
            </div>
          )}

          <div className="border rounded-xl p-4 mb-8 text-left" style={{ background: "var(--cc)", borderColor: "var(--cab)" }}>
            <p className="text-xs leading-relaxed" style={{ color: "var(--cm)" }}>
              <strong style={{ color: "var(--cs)" }}>{t.warning}</strong> {t.warningText}
            </p>
          </div>

          <Link href="/" className="inline-flex items-center gap-2 text-sm font-medium transition-colors rounded-xl px-6 py-3"
            style={{ color: "var(--cm)", border: "1px solid var(--ce)" }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--ct)"; (e.currentTarget as HTMLElement).style.borderColor = "var(--cab)"; }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--cm)"; (e.currentTarget as HTMLElement).style.borderColor = "var(--ce)"; }}>
            {t.orderAnother}
          </Link>
        </div>
      </main>

      <footer className="border-t py-6 text-center" style={{ borderColor: "var(--ce)" }}>
        <p className="text-xs" style={{ color: "var(--cf)" }}>{t.footer}</p>
      </footer>
    </div>
  );
}

export default function SuccessPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen flex items-center justify-center" style={{ background: "var(--cb)" }}>
        <div className="w-8 h-8 border-2 border-t-transparent rounded-full animate-spin" style={{ borderColor: "var(--ca)", borderTopColor: "transparent" }} />
      </div>
    }>
      <SuccessContent />
    </Suspense>
  );
}
